version: '3.8'
services:
  # web:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  db:
    image: "nouchka/sqlite3"
    volumes:
      - ./data:/root/db
    environment:
      - SQLITE_DATABASE=shop-basket.db
